# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180202_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
