# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180203_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['subname'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='category',
            name='subname',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
