# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180207_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subname',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Подкатегория'),
        ),
    ]
