# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180222_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена'),
        ),
    ]
