# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180315_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='search_index',
        ),
        migrations.RemoveField(
            model_name='category',
            name='search_index',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='search_index',
        ),
    ]
