# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20180315_2124'),
    ]

    operations = [
        TrigramExtension(),

        UnaccentExtension(),

        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_index',
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
