# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_search_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_index',
        ),
    ]
